android.useAndroidX=true

# Jetifier: turn off unless you *must* support a legacy support-library dependency.
# If something breaks, flip back to true.
android.enableJetifier=false

android.nonFinalResIds=true
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

org.gradle.parallel=true
org.gradle.caching=true
#android.defaults.buildfeatures.resvalues=true
#android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
#android.usesSdkInManifest.disallowed=false
#android.uniquePackageNames=false
#android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
#android.builtInKotlin=false
#android.newDsl=false